context:
  name: csp-bot-commands
  version: "2.0.0"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/csp-bot-commands/csp_bot_commands-${{ version }}.tar.gz
  sha256: 56a5119d5482ed11bd452dc4ba8696cd25f850ba045caefa20651ff74d71a06f

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - chatom >=0.2.0
    - csp-bot >=2,<3

tests:
  - python:
      imports:
        - csp_bot_commands
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Miscellaneous commands for csp-bot
  homepage: https://github.com/csp-community/csp-bot-commands/wiki
  repository: https://github.com/csp-community/csp-bot-commands

extra:
  recipe-maintainers:
    - timkpaine
