context:
  name: csp-bot-commands
  version: "1.0.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/csp-bot-commands/csp_bot_commands-${{ version }}.tar.gz
  sha256: c45c044e46afe90ce0c72ab6c831be36724e14712d3c3ef54c29b26bc5254c54

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - csp-bot >=1,<2

tests:
  - python:
      imports:
        - csp_bot_commands
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Miscellaneous commands for csp-bot
  homepage: https://github.com/csp-community/csp-bot-commands/wiki
  repository: https://github.com/csp-community/csp-bot-commands

extra:
  recipe-maintainers:
    - timkpaine
